id: P8F99DCD7
initial_creation_type: input
source_metadata:
  title: Termas
  language: nl
  description: 'A collection of spiritual treasures or terma (gter ma), which were
    reportedly hidden by Guru Padmasambhava and Yeshe Tsogyal, either in the earth
    and in the minds of disciples, and then revealed at the appropriate time by ‘treasure
    revealers’ or tertön (gter ston):'
  volume:
    3371d0001a02451b9b72239963a272dd:
      title: Daily Practice of Vajrakīla
      parent: Apang Tertön
    6f25a5404d7a444d8202291bdbf4d142:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Chöje Lingpa
    204253e7665448cbacf45886ea2f12e2:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Chöje Lingpa
    c091d7c6271c4825b1d32ae0940eebcc:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Chokgyur Dechen Lingpa
    9f9097cb50cb426786b7ff6477a678e9:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Chokgyur Dechen Lingpa
    2bbcf17cc0ef406b8922ccadf7d0d7ad:
      title: The Lament of Rudra
      parent: Chokgyur Dechen Lingpa
    3e300674f70f446083d16b9d4ec97a08:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    0af4562a96024365bbccee3adc28df10:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    ffeaadc0f5df47128716f92a790ca38a:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    667a83a737f9467fa2eac57ad23a8860:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    f6eff830029a4398a92c9954edaf32f1:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    bec156e8a43b41ecadfc68f5e2cfcf97:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Chokgyur Dechen Lingpa
    1037f59f3a024fa0aee2c3b69089db34:
      title: Concise Daily Practice of Vajrasattva
      parent: Chokgyur Dechen Lingpa
    eb7314caf62842c8ab4681fb5be2190c:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chokgyur Dechen Lingpa
    9923d8e5eeba4d5fa4944cfb25c5f6d5:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    a085b528286141219c200e2a684fddd9:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Do Khyentse
    5633dbe205444cad9fca034c975e679f:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    5833b3ee37f7447f864bb436aab5232e:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Do Khyentse
    b48fa97ec22e46978cc0d69f2fbdd613:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Do Khyentse
    b6c783e6038c485e8077ba86613e75ba:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    2c8051b9bfe64adbb188bf5516d10f72:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Dorje Dechen Lingpa
    4bb28fc86c5145caaa1dd302fe362261:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Dudjom Lingpa
    7e5a5ec5f4834aa8a21865beb61ad24f:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Rinpoche
    688421a95bfa4afd98fde72b501bdb6f:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    85e1b1ccaab74123ad22fdcbde8f077d:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Guru Chöwang
    4b57ac8a0c6f418480fc2e15ef3be0fe:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Guru Chöwang
    04f66378b1484d45abf9c7b0091e9c70:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Guru Chöwang
    e000cf5118cf4e07be1a0300823ed078:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Guru Chöwang
    be8d9d877cb14ff2a396801cc6e63848:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Guru Chöwang
    99ca56a7b3a4453a87a95721d602faad:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Guru Chöwang
    725c933747de4fd191aaefc656503e8e:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Gyarong Khandro
    520aa6b4600546fa9fbc127bc0b2862a:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Jamyang Khyentse Chökyi Lodrö
    1e9395b713c344e88ce34566163854ec:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    29be41d05cef4cb898062a6a5296a227:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Jamyang Khyentse Wangpo
    854cd335563d4af1830b7ed8a1c2fbf9:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    6edb7c038d8b4c8a8e21d4a727661357:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Jamyang Khyentse Wangpo
    c0617bfcf26544c0bffe988a900075a7:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Jatsön Nyingpo
    b6d3fa19c84b4fcc9e21312a4ccf1af7:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Jatsön Nyingpo
    cdaaf1e7bddb46cbadaa7e525bffb2ab:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Jigdral Tutop Lingpa
    7222235b1a97478f9181da7525f57379:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Jigme Lingpa
    dc0ba1b86de54c0a9d0735e37e6b6b23:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    f0de1b8f3d34442aa30504341e900578:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    0dc122cc914b450f9fed90e6c54c708a:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Jigme Lingpa
    9afbae0435844c1fae16fd1a06eccf33:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Jigme Lingpa
    60cc2d52cc35430e95da1257fcee1206:
      title: Brief Prayer of the Feast Gathering
      parent: Jigme Lingpa
    4b58a63d8e604f998123a7cae1faf1d3:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    697dfdc69fa24a4585a815e92563f7d3:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Jigme Lingpa
    262bd78d561f4d8f83263d0335f8b350:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Jigme Lingpa
    9deda88d1d894de497127c30425e43c0:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Jigme Lingpa
    5bc859a52c7149309835187282606c53:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Jigme Lingpa
    6a63806de6a04531b1327fb43944a4a9:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Jigme Lingpa
    d1212cb1a76f4ca89ec11c05528e7941:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Jigme Lingpa
    81fac00536e44552a96469b251707b42:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Jigme Lingpa
    6f6cebfdc7a147f3a976aa63af42511e:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Jigme Lingpa
    03bab13b41904114b4a672f9f4faba44:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Jigme Lingpa
    75ddcb9110574eea98f8a2a14fabe4e9:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Jigme Lingpa
    841924dd3de04cd7a60876a13e5d5aea:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Jigme Lingpa
    4d1e382c4a044277b0a4cb351c2473a8:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Jigme Lingpa
    ad5c0587b98b432bb7e63fab7a9cb5e7:
      title: Vajra Verses on the Natural State
      parent: Jigme Lingpa
    9bc16297b1094408ab643758dfc152de:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Karma Lingpa
    3cb66a80ce17418b95ef3f14e9abb7c0:
      title: The Benefits of the Vajra Guru Mantra and an Explanation of Its Syllables
      parent: Karma Lingpa
    f487f23c1ede49f0aee33b7266e5e846:
      title: The Root Verses on the Six Bardos
      parent: Karma Lingpa
    8de34a8579ee4f1b867db28da94a7790:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Khenchen Jigme Phuntsok
    32edb7766fe3409ba93eab6990da4383:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Khenchen Jigme Phuntsok
    5506618bc1ba4ea3b11f22fe4af3c447:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Lhatsün Namkha Jigme
    2e417040687449b881041ad0888ea9a2:
      title: Maṇḍala Offering from Longsal Dorje Nyingpo
      parent: Longsal Nyingpo
    bff98dd64ab94c2f98af6d283ed858cd:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Ngakchang Shakya Zangpo
    eb786017891f47db8f97597181836f5a:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Nyala Pema Dündul
    5ca09d97a877498488b593165f214539:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    a6520eb2395846ad85ec573686234d19:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    69989c514a2a43518a2c474288bf792c:
      title: The Pointing-the-Staff Instruction
      parent: Nyang Ral Nyima Özer
    83431069b94c44f4b217499ab2458e4a:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Orgyen Lingpa
    eaeef211c1c04ebcba5a00bb7af2c7a7:
      title: Yeshe Tsogyal's Prayer
      parent: Pema Lingpa
    1f3cd7e6abe44a0f8268d48ad5609fcd:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Ratna Lingpa
    dc560dce0bc84b349d25a6eecb8bd962:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Rigdzin Gödem
    601d4e526bef4de9881b36e06aa14f2b:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Rigdzin Gödem
    8bd3743ea02b4ee9b245f66fa68e9b3d:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Rigdzin Nyima Drakpa
    14a9568c4dd44229b849dd7d515c36da:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Samten Lingpa
    15e1d62e91f44de38531323dfb1ece1a:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sera Khandro
    034fcd5a64f6457d91bfaf991f1fd495:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sera Khandro
    7adc980e224d4e1d97462ac82e4481ae:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Sherab Özer
    c246125280b44f9ab7ec990653726e8d:
      title: Brief Sukhāvatī Aspiration
      parent: Tertön Mingyur Dorje
    d37482f7b69e421e88c4237c07b99224:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Tertön Mingyur Dorje
    ba13211fea114a6d837e9550f5428cff:
      title: Prayer to Behold Amitābha in Dreams
      parent: Tertön Mingyur Dorje
    ec54284c7be04727b1fdab42c84b682e:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Tertön Sogyal
    2cbe62dd4dc841f79a2b1e8790a439cb:
      title: Sādhana of Mañjughoṣa
      parent: Tertön Sogyal
    6d5f080dc5654ac8a5bcbd94a9be55a2:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Tertön Sogyal
    2dd1bb8d168a4de6b12da29550df1512:
      title: The Guru Yoga of the Profound Path
      parent: Tertön Sogyal
    f3b70c45ae7949678be3b4105cc7fb13:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Tertön Sogyal
    0a3d1557dc86490ca350b7e9e77fb152:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Tertön Sogyal
    37e26cfa585341b6a18fac7e1c05d88e:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Tertön Sogyal
    dc40f81dd88c420dbb3ee75095b5ea91:
      title: The Wisdom Mind Practice of One Kīla
      parent: Tertön Sogyal
    5099c6039e3e477980c1d58dd5b6ecf0:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Tulku Zangpo Drakpa
    b1e6e2e3bd034c98b5a9d026a6b7f052:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Tulku Zangpo Drakpa
    f88c7d28af1f48bb97c73ee84b478c6e:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Tulku Zangpo Drakpa
    8c3f679cd7e848359aff872e2366ed5a:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Tulku Zangpo Drakpa
    c7c2e697280b4d6e8f935e87aa0c4880:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Tulku Zangpo Drakpa
    6d5868e2728d49bea5fb6e43942e32c4:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Tulku Zangpo Drakpa
    4d650bbd456745b19d37439f3c35be0e:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Tulku Zangpo Drakpa
    ad029b96ed1f4ade80144f878b2700cd:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Tulku Zangpo Drakpa
created_at: '2022-03-01T06:17:48.634356'
last_modified_at: '2022-03-01T06:17:48.634359'
